# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8307a1889037c94012b708158c4003c8b92551c1edd43ddfd122e3296d993adcc2236a546b4279bb26e83cb4b23040e6209e23344c23aeadb24b6f2895e68703

test:
  secret_key_base: 830c15999f48b8aeec6d32859c6f0a0c57477a6e53c089030b938bab188aeb38f0a1ef36ecc050dc938e49f4276c12cc3497e13edd49075deaadd560fad272f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
